### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by probepark** [start-k8s/study#3]
- [sidecar pattern](https://kubernetes.io/blog/2015/06/the-distributed-system-toolkit-patterns/)
- [logging architeture](https://kubernetes.io/docs/concepts/cluster-administration/logging/)
- [sidecars and daemonset](https://wecode.wepay.com/posts/scds-battle-of-containerization)

**Comment by keyolk** [comment]
ELK가 일반화되긴 했는데
가치 높은 로그야 잘 indexing 해서 넣는게 중요하겠지만
error 로그나 event 성 로그에 대해선 비용이 너무 큰것 같은 느낌이 있는것 같음

https://grafana.com/oss/loki

prometheus like 하게 잘포장된거 같아서 써봤는데 그럭저럭 괜찮은듯...
불만은 덕분에 log agent가 너무 많아지는것 같고 복잡해짐

access log 같은건 보통 가치가 높으니까 ELK로 보내고
error log 같은건 loki로 보내고 ...
